#ifndef RTE_SEAT_MANAGER_H
#define RTE_SEAT_MANAGER_H

#define MULTI_STATE_BTN_INIT   0
#define MULTI_STATE_BTN_MINUS -1
#define MULTI_STATE_BTN_PLUS   1

#define MOTOR_STEP_PLUS   1
#define MOTOR_STEP_MINUS  0

#define SENSOR_POSITION_STEP_0 0
#define SENSOR_POSITION_STEP_1 1
#define SENSOR_POSITION_STEP_2 2
#define SENSOR_POSITION_STEP_3 3
#endif